<?php

namespace App\Repository;

/**
 * AttributSpatialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributSpatialRepository extends \Doctrine\ORM\EntityRepository
{
}
