<?php

namespace App\Repository;

/**
 * ChartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChartRepository extends \Doctrine\ORM\EntityRepository
{
}
