<?php

namespace App\Repository;

/**
 * DataSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSourceRepository extends \Doctrine\ORM\EntityRepository
{

    public function findDataSourceListForUserCre($userCre=0) {
        $queryBuilder =  $this->getEntityManager()->createQueryBuilder();

        return $queryBuilder->select('ds')
                ->from('App\Entity\DataSource','ds')
                ->andWhere('ds.userCre = :val')
                ->setParameter('val', $userCre)
                ->orderBy('ds.id', 'ASC')
        ;
    }    

}
