<?php

namespace App\Repository;

/**
 * DataListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataListRepository extends \Doctrine\ORM\EntityRepository
{
}
