<?php

namespace App\Repository;

/**
 * DataSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
