index:
    path:      /
    controller: App\Controller\ChartController::index

index2:
    path:      /{_locale}
    controller: App\Controller\ChartController::index
    requirements:
        _locale: en|fr

chart:
    resource: './routes/chart.yaml'
    prefix: /{_locale}/chart
    requirements:
        _locale: en|fr

# URLs protegees par /scientific
chart_scientific:
    resource: './routes/chart_scientific.yaml'
    prefix: /{_locale}/scientific/chart
    requirements:
        _locale: en|fr

# URLs protegees par /admin
chart_scientific_plus:
    resource: './routes/chart_scientific_plus.yaml'
    prefix: /{_locale}/scientific+/chart
    requirements:
        _locale: en|fr

# URLs protegees par /admin
data_sources:
    resource: './routes/data_sources.yaml'
    prefix: /{_locale}/admin/data-sources
    requirements:
        _locale: en|fr

# URLs protegees par /scientifique+
mc_data_list:
    resource: './routes/data_list.yaml'
    prefix: /{_locale}/scientifique+/data-list
    requirements:
        _locale: en|fr

#--------
# USERS
#--------

user_show:
  path:  /users/show/{id}
  controller: App\Controller\UserController::show
  requirements:
    id: \d+

#----------------
# USERS (ADMIN)
#----------------

user_list:
  path:     /users/list
  controller: App\Controller\UserController::index

user_edit:
  path:     /users/edit/{id}
  controller: App\Controller\UserController::edit
  requirements:
    id: \d+

user_delete:
  path:     /users/delete/{id}
  controller: App\Controller\UserController::delete
  requirements:
    id: \d+

user_register:
  path:     /users/register
  controller: App\Controller\UserController::register
  requirements:
    id: \d+
